### ISSUE TITLE
Plone 5.2.2 installer: Zope-releases-4.5.1-versions.cfg missing

### ISSUE THREAD

**Issue by tobiasherp** [plone/Installers-UnifiedInstaller#107]
I'm currently trying the UnifiedInstaller for Plone 5.2.2 (cloned the `master` branch), and the buildout fails because of a missing file `Zope-releases-4.5.1-versions.cfg`, which is *extended* by `release-5.2.2-versions.cfg`:

    Traceback (most recent call last):
      File ".../Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2173, in main
        user_defaults, command, args)
      File ".../Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 370, in __init__
        data_buildout_copy, override, set()))
      File ".../Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1826, in _open
        downloaded))
      File ".../Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1823, in _open
        downloaded)
      File ".../Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1784, in _open
        fp = open(filename)
    IOError: [Errno 2] No such file or directory: '.../Plone/zinstance/Zope-releases-4.5.1-versions.cfg'

Seems we'd need to add this to the buildout scripts there, right?
(For now, the URL to get this file would help me.)

**Comment by mauritsvanrees** [comment]
That would be this URL:

https://zopefoundation.github.io/Zope/releases/4.5.1/versions.cfg
