### ISSUE TITLE
Plone 5 UnifiedInstaller breaks if pip.conf in $HOME has user=true.

### ISSUE THREAD

**Issue by idgserpro** [plone/Installers-UnifiedInstaller#44]
If you have ```pip.conf``` in your $HOME with:

```
[install]
user = true
```

You get the following error when running the UnifiedInstaller:

```
Detailed installation log
Starting at Ter Out  6 10:12:42 BRT 2015
Traceback (most recent call last):
  File "virtualenv.py", line 2363, in <module>
    main()
  File "virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home//Pl...stance/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

You need to comment/remove the ```user=true``` line to make the UnifiedInstaller work.

**Comment by idgserpro** [comment]
This seems to be virtualenv related. Check https://github.com/pypa/virtualenv/pull/803. Virtualenv 14.0.0 fixes it.

**Comment by smcmahon** [comment]
Thanks!
