### ISSUE TITLE
Error installing 5.0.8-r1 on macOS 10.13

### ISSUE THREAD

**Issue by meshde** [plone/Installers-UnifiedInstaller#69]
Hello!

I am new to the Open Source Community, so please forgive me and guide me if I'm not following standard guidelines while opening this issue.

I downloaded the UnifiedInstaller from [here](https://plone.org/download/releases/5.0.8), unzipped the file and ran `./install.sh` according to [this](https://docs.plone.org/manage/installing/installation.html#plone-unified-unix-installer).

I'm getting an error as follows

> Continue with the command line:
> 
> install.sh standalone \
>     --target="/Users/meshde/Plone" --password="*****..." 
> 
> 1) Yes
> 2) No
> #? 1
> 
> Testing /usr/bin/python2.7 for Zope/Plone requirements....
> /usr/bin/python2.7 looks OK. We will use it.
> 
> Rootless install method chosen. Will install for use by system user meshde
> 
> 
> Detailed installation log being written to /Users/meshde/Plone-5.0.8-UnifiedInstaller-r1/install.log
> Installing Plone 5.0.8 at /Users/meshde/Plone
> 
> Creating Python virtual environment.
> New python executable in /Users/meshde/Plone/zinstance/bin/python
> Installing setuptools, pip, wheel...done.
> Installing zc.buildout in virtual environment.
> Unpacking buildout cache to /Users/meshde/Plone/buildout-cache
> Copying Plone-docs
> Copying buildout skeleton
> Building Zope/Plone; this takes a while...
> Buildout returned an error code: 1; Aborting.
> Buildout failed. Unable to continue
> 
> Installation has failed.
> See the detailed installation log at /Users/meshde/Plone-5.0.8-UnifiedInstaller-r1/install.log
> to determine the cause.

Just in case, I have also attached the `install.log` file.
[install.log](https://github.com/plone/Installers-UnifiedInstaller/files/1681699/install.log)

The Traceback in the `install.log` file is as follows:

> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 366, in _handle_tasks
>     debug('task handler got sentinel')
> TypeError: 'NoneType' object is not callable
> 
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
>     debug('worker handler exiting')
> TypeError: 'NoneType' object is not callable
> 
> Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2310, in main
>     **kw
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 412, in run
>     self.easy_install(spec, not self.no_deps)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
>     return self.install_item(None, spec, tmpdir, deps, True)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
>     dists = self.install_eggs(spec, download, tmpdir)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 882, in install_eggs
>     return self.build_and_install(setup_script, setup_base)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in build_and_install
>     self.run_setup(setup_script, setup_base, args)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1136, in run_setup
>     run_setup(setup_script, args)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
>     raise
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
>     yield
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
>     saved_exc.resume()
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
>     six.reraise(type, exc, self._tb)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
>     yield saved
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
>     yield
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
>     _execfile(setup_script, ns)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
>     exec(code, globals, locals)
>   File "/var/folders/vw/wj88jg657616mx9tz9mgszsr0000gn/T/easy_install-2iu0Ez/Pillow-3.4.2/setup.py", line 753, in <module>
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 170, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 156, in call_command
>     self.run_command(cmdname)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 111, in build
>     self.run_command('build_ext')
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
>     self.build_extensions()
>   File "/var/folders/vw/wj88jg657616mx9tz9mgszsr0000gn/T/easy_install-2iu0Ez/Pillow-3.4.2/setup.py", line 521, in build_extensions
> ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
> An error occurred when trying to install /Users/meshde/Plone/buildout-cache/downloads/dist/Pillow-3.4.2.zip. Look above this message for any errors that were output by easy_install.
> While:
>   Installing instance.
>   Getting distribution for 'Pillow==3.4.2'.
> 
> An internal error occurred due to a bug in either zc.buildout or in a
> recipe being used:
> Traceback (most recent call last):
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2123, in main
>     getattr(buildout, command)(args)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 796, in install
>     installed_files = self[part]._call(recipe.install)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1553, in _call
>     return f()
>   File "/Users/meshde/Plone/buildout-cache/eggs/plone.recipe.zope2instance-4.2.22-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 113, in install
>     installed.extend(self.install_scripts())
>   File "/Users/meshde/Plone/buildout-cache/eggs/plone.recipe.zope2instance-4.2.22-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 617, in install_scripts
>     requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
>   File "/Users/meshde/Plone/buildout-cache/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
>     allow_hosts=self.allow_hosts)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 913, in install
>     return installer.install(specs, working_set)
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 665, in install
>     for dist in self._get_dist(requirement, ws):
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 563, in _get_dist
>     dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
>   File "/Users/meshde/Plone/zinstance/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
>     [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
> ValueError: need more than 0 values to unpack

**Comment by meshde** [comment]
Running `xcode-select --install` before the installation solves the issue.
