### ISSUE TITLE
Remove Products.DocFinderTab from Plone 5.2 develop.cfg (or fix it)

### ISSUE THREAD

**Issue by avoinea** [plone/Installers-UnifiedInstaller#86]
Within Plone 5.2rc1 UnifiedInstaller, after running buildout with `develop.cfg` and trying to start instance I get the following error:

```python
$ bin/instance fg
/plone/buildout-cache/eggs/Products.CMFPlacefulWorkflow-2.0.0-py3.7.egg/Products/CMFPlacefulWorkflow/permissions.py:5: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
Traceback (most recent call last):
  File "/plone/instance/parts/instance/bin/interpreter", line 271, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/serve.py", line 219, in <module>
    sys.exit(main() or 0)
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/serve.py", line 216, in main
    return command.run()
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/serve.py", line 183, in run
    global_conf=vars)
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/serve.py", line 207, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/plone/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/run.py", line 67, in make_wsgi_app
    starter.prepare()
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/starter.py", line 40, in prepare
    self.startZope()
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/Startup/starter.py", line 96, in startZope
    Zope2.startup_wsgi()
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/__init__.py", line 49, in startup_wsgi
    _startup()
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/Zope2/App/startup.py", line 86, in startup
    OFS.Application.import_products()
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/OFS/Application.py", line 379, in import_products
    import_product(product_dir, product_name)
  File "/plone/buildout-cache/eggs/Zope-4.0b10-py3.7.egg/OFS/Application.py", line 389, in import_product
    global_dict, global_dict, ('__doc__', ))
  File "/plone/buildout-cache/eggs/Products.DocFinderTab-1.0.5-py3.7.egg/Products/DocFinderTab/__init__.py", line 21, in <module>
    from permissions import ViewDocPermission, ViewDocDefaultRoles
ModuleNotFoundError: No module named 'permissions'
```

**Comment by avoinea** [comment]
Ops @smcmahon already removed it in https://github.com/plone/Installers-UnifiedInstaller/commit/b744f441c6ba4c34babc450749ed60d7f75f82a9
